Updated typo on equals for request
Including specification of version 1.5.0 in requirements file to avoid TypeError shown below due to tasks version being installed as 2.0.0...

TypeError: Invalid constructor input for ListTasksRequest: 'projects/PROJECT_ID/locations/LOCATION/queues/ads-queue'